### ISSUE TITLE
ios 显示问题

### ISSUE THREAD

**Issue by TiddlyWorkspace** [ikkz/anki-eco#1]
模版在ios端不能正确使用

**Comment by ikkz** [comment]
> 模版在ios端不能正确使用

具体啥问题

**Comment by ikkz** [comment]
@TiddlyWorkspace  感谢反馈，已修复，可以在下面任意链接下载最新

https://github.com/ikkz/anki-templet/releases/tag/1.0.1

https://ankiweb.net/shared/info/1939456021
