### ISSUE TITLE
小屏幕上公式显示不完整，如图

### ISSUE THREAD

**Issue by TiddlyWorkspace** [ikkz/anki-eco#12]
![image](https://github.com/user-attachments/assets/6c61b102-6142-4004-aebc-cfb03834a417)
![image](https://github.com/user-attachments/assets/e54ea953-d544-403a-96c3-594fcbf138cb)

**Comment by ikkz** [comment]
发一下题目文本看看

**Comment by TiddlyWorkspace** [comment]
> 发一下题目文本看看

1．已知函数\(f(x)\)满足对一切\(x_{1} ,x_{2} \in {\rm R}\)都有\(f\left(x_{1} +x_{2} \right)=f\left(x_{1} \right)+f\left(x_{2} \right)-2\)且\(f(1)=0\),当\(x\gt 1\)时有\(f(x)\lt 0\).
(1)求\(f(-1)\)的值;
(2)判断并证明函数\(f(x)\)在\(R\)上的单调性;
(3)解不等式:\([f(x^{2} -2x)]^{2} +2f(x^{2} -2x-1)-12\lt 0\).

**Comment by TiddlyWorkspace** [comment]
> 发一下题目文本看看

公式太长了就会这样，要么拆成两个，要么看能不能题目部分左右滑动一下

**Comment by ikkz** [comment]
https://github.com/ikkz/anki-template/actions/runs/11975753693
下面有个 APKGs 你下载看看有没有解决

**Comment by TiddlyWorkspace** [comment]
> https://github.com/ikkz/anki-template/actions/runs/11975753693
> 
> 下面有个 APKGs 你下载看看有没有解决

解决了，效率太高了
