### ISSUE TITLE
关于Tags的建议

### ISSUE THREAD

**Issue by hihvan** [ikkz/anki-eco#17]
更新后发现多了一个Tags的字段，并且会在题目右边显示。我在想，为什么不直接在右边显示自带的标签呢。
自带的标签一样显示的同时。还可以筛选检索。我想这样既减少了字段，也避免了字段与标签的重复，也方便检索浏览整理卡片。
![截图_20241125_103808](https://github.com/user-attachments/assets/d8b22704-f777-4346-8716-480c3ca5d295)
例如：知识点模板。
![截图_20241125_104216](https://github.com/user-attachments/assets/63223f14-2f57-4a81-8df3-e412ff0505c4)

**Comment by ikkz** [comment]
应该是个 bug，确实要使用自带的 tags， 等会修一下

**Comment by ikkz** [comment]
下载最下面的 APKGs 看看还有没有问题
https://github.com/ikkz/anki-template/actions/runs/12004697651

**Comment by ikkz** [comment]
https://github.com/ikkz/anki-template/releases
