### ISSUE TITLE
隐藏倒计时、“About”后出现 显示问题

### ISSUE THREAD

**Issue by hihvan** [ikkz/anki-eco#2]
在隐藏倒计时、“About”后，卡片正面下方会出现一个白色区域，在 学习 界面一样会出现，而且不因夜间模式开启关闭 而变化。
![截图_20241025_125257](https://github.com/user-attachments/assets/d36d9560-2b6c-428b-8e20-2cde0f3a6731)

![截图_20241025_125111](https://github.com/user-attachments/assets/2293db0c-d968-4a6d-9fb8-829b385685af)
![截图_20241025_125135](https://github.com/user-attachments/assets/761320d2-4e66-4aae-a20d-392a87cf59f4)

**Comment by hihvan** [comment]
卡片背面无此问题，您的模板非常漂亮。

**Comment by ikkz** [comment]
感谢反馈，明天修复。

另外之前已经做了中文版，看截图你似乎也有这个需求，明天有空的话也会整理一下发布。

**Comment by ikkz** [comment]
@hihvan 黑暗模式的问题已更新，中文得明天了

**Comment by hihvan** [comment]
> @hihvan 黑暗模式的问题已更新，中文得明天了

感谢更新。
导入后ankidroid显示正常，但是电脑不显示了。
![截图_20241026_233615](https://github.com/user-attachments/assets/d73f52df-7dc1-41de-b931-6bd5ba6d0e0d)
期待明天更新🌸

**Comment by ikkz** [comment]
@hihvan 再试试这个版本

https://github.com/ikkz/anki-template/blob/main/mcq/front.html

**Comment by hihvan** [comment]
@ikkz 完美perfect

**Comment by ikkz** [comment]
@hihvan 中文版已发布 https://github.com/ikkz/anki-template/releases

**Comment by TiddlyWorkspace** [comment]
选择题功能实现得非常完美了，想把模板扩展到更多应用场景，即不在option填入内容的时候能当成正常的QA卡片模板使用。当我在尝试时，我在answer字段添加了带数学公式的内容，公式渲染会出现问题，能否优化一下呢![image](https://github.com/user-attachments/assets/f8993167-8031-410f-8bc8-e275248bb804)
