### ISSUE TITLE
所有模板宽屏支持和选择题选项排版

### ISSUE THREAD

**Issue by TiddlyWorkspace** [ikkz/anki-eco#21]
选项自动排版成合适的列数，以适应不同长度的选项以及不同设备
![image](https://github.com/user-attachments/assets/391bd632-5875-4cb5-a3c4-9887c4110e96)

**Comment by ikkz** [comment]
不确定效果好不好，因为选项上还有错选漏选和ABCD的标记，加上就算在电脑/pad上最宽也只有 560px

你是在宽屏上使用较多吗？

**Comment by TiddlyWorkspace** [comment]
对，一般情况不受影响，主要是有一种特殊情况，当选项部分全是图片时，显示效果会有一点影响
![image](https://github.com/user-attachments/assets/9505f9e4-01e0-4368-b462-31e0b9d1656e)

**Comment by TiddlyWorkspace** [comment]
如果排成一列或者两列可能好点，当然主要是我稍微修改了一下总的宽度以适应宽屏

**Comment by ikkz** [comment]
所以需要在支持宽屏之后，支持选项分列排版才有意义

**Comment by ikkz** [comment]
查阅了一些资料之后还是决定不支持更大的展示宽度了，过宽反而导致阅读困难和记忆效果不佳。

相关链接：
- https://www.xmind.design/48f1af1c7f654ca085978db486dc438e
- https://baymard.com/blog/line-length-readability
