### ISSUE TITLE
FlipToBack

### ISSUE THREAD

**Issue by ferreirasilv** [ikkz/anki-eco#25]
Hello everything is fine? I don't know English very well, but I would like to make a suggestion, would it be possible to turn the back of the card when selecting the correct (or wrong) alternatives automatically? I saw this in a template, I thought it was brilliant, if you could take a look. Thanks. ^^

**Comment by ikkz** [comment]
yes, when the type is single choice question and the option `Hide the number of answer at the top` is off, flipping to back automatically is more convenient

I will add this feature when I have free time

**Comment by ikkz** [comment]
You can download the latest version at https://github.com/ikkz/anki-template/releases

**Comment by ferreirasilv** [comment]
Ohh, thanks. ✨🥳
