### ISSUE TITLE
answer字段公式渲染问题

### ISSUE THREAD

**Issue by TiddlyWorkspace** [ikkz/anki-eco#3]
爱不释手，选择题功能实现得非常完美了，想把模板扩展到更多应用场景，不在option填入内容的时候能当成正常的QA卡片模板使用。当我在尝试时，我在answer字段添加了带数学公式的内容，此时公式渲染会出现问题，能否优化一下呢，非常感谢您的工作![image](https://github.com/user-attachments/assets/f8993167-8031-410f-8bc8-e275248bb804)

**Comment by ikkz** [comment]
很开心我的模板对你的学习有所帮助。

计划新增一个专门的问答题模板，会继承选择题模板的外观和大部分设置，有其他的功能建议可以在 #4 下回复。

如果能帮忙推广，我会有更大的动力实现新的模板：）

**Comment by ikkz** [comment]
@TiddlyWorkspace  已新增basic模板，下载文件夹中的 release.apkg 即可
https://github.com/ikkz/anki-template/tree/main/basic

**Comment by TiddlyWorkspace** [comment]
非常感谢，您的模版对我的学习产生了巨大的帮助，在实际使用过程中，由于一些个性化需求，经常会需要增添一些额外字段来展示一些其他的信息，您的模板专业度极高，使得完成自定义新的字段比较困难，您是否考虑出一个教程或者在代码中进行部分注释帮助代码水平一般的使用者能更好使用您的模板呢？

另外，您的选择题模版让人惊艳，我查看了代码发现问答题是在选择题模版上进行了修改，其实在使用 anki 过程中我收集了很多模板，但一直想找到一款模版能同时担任选择和问题功能且有兼具较高颜值，您的模版让人眼前一亮，请问一下能否将选择功能和问答功能合为一体呢，就是在选择题模板中增加一个条件判定， option 字段不填入内容的时候 answer 字段不进行映射，正常显示字段内容即可，这样添加笔记就不用频繁切换模版，可用性大大增加了，特别是有时候批量添加笔记后，更改某些笔记的模板需要重新上传整个集合

**Comment by ikkz** [comment]
1. 目前模板的代码设计还不支持自定义新字段，需要一些开发工作来支持字段插槽，可以订阅这个 issue #5，最迟这个月完成支持

2. 暂时没有计划将选择题和简单问答题的功能合并，会增加选择题模板的使用复杂度，需要用户额外理解这个隐藏功能；后续维护也不是很方便，因为后面的新功能、问题修复都需要考虑这种用法。是否可以在添加时使用快捷键例如 Mac 的 `Command + N` 来快捷切换模板，我试验下来是可以在三次按键内完成模板切换

**Comment by TiddlyWorkspace** [comment]
那选项部分可以合并到一个字段用分隔符进行分隔吗，例如比较常见的利用||隔开不同的选项

**Comment by ikkz** [comment]
这个也不太好实现，如果||在段落，颜色，粗体中间不是很好完美拆分，导致格式出问题

如果是为了输入方便，可以按 tab 键直接跳转到下一个字段输入

**Comment by TiddlyWorkspace** [comment]
> 这个也不太好实现，如果||在段落，颜色，粗体中间不是很好完美拆分，导致格式出问题
> 
> 如果是为了输入方便，可以按 tab 键直接跳转到下一个字段输入

好的，感谢您的耐心回复

**Comment by ikkz** [comment]
@TiddlyWorkspace 现在模板的字段部分有更好的可读性了，你可以修改这部分内容实现自定义字段显示

<img width="548" alt="图片" src="https://github.com/user-attachments/assets/6037218a-ea96-44b7-bbc9-8d0aca06f84a">

例如
```
<div id="at-field-note">{{note}}</div>
```
添加字段extraField，并修改为
```
<div id="at-field-note">
{{note}}
{{extraField}}
</div>
```
即可在 note 下方展示 extraField

最新版在这里下载 https://github.com/ikkz/anki-template/releases

**Comment by TiddlyWorkspace** [comment]
感谢你的指导，非常有用，经过一段时间的体验，基于个人使用感受，以下信息可能有助于改进用户体验。
1⃣️若卡片正面有一个由按钮控制的提示字段，将会对学习和复习非常有帮助
2⃣️以数学类卡片为例，复习过程中经常遇到解析过长，需要频繁上下滑动，以查看题干中的信息，固定住题干区域或者让笔记区域可以滑动将会非常有用
3⃣️复习数学相关卡片时也会遇到一个题目中包含多个小题的情况，我目前的解决方案是使用按钮切换至不同字段以减少滑动的频率，如图。
希望我的反馈对你的改进能起到帮助，也希望模板功能越来越完善

![image](https://github.com/user-attachments/assets/57067f3b-837a-4478-8f89-2ade60237fa3)

**Comment by ikkz** [comment]
这些点可以分开提 issue 吗，方便讨论和跟踪进度
