### ISSUE TITLE
Add a template setting to remove the letters in the question options and the answer

### ISSUE THREAD

**Issue by aedriandecastro** [ikkz/anki-eco#35]
![image](https://github.com/user-attachments/assets/96e07a08-dd3d-462b-8861-1e0ddee73c1e)

**Comment by ikkz** [comment]
The expected display of these letters should look like [this](https://github.com/ikkz/anki-template?tab=readme-ov-file#screenshots) and will be fixed soon along with #34

**Comment by ikkz** [comment]
There are currently no plans to add an option to toggle the display of answer, as this would make the settings page more complex. If you have a specific reason, please explain it in detail.

**Comment by aedriandecastro** [comment]
Thank you for the quick response. I think adding more customization options would be nice but I understand that it would make the template settings more complex. For my use case, having the option to remove them would simplify the appearance of the card (less distractions) and it would allow for more real estate for the content, which is more important than the design of the card.

**Comment by aedriandecastro** [comment]
> The expected display of these letters should look like [this](https://github.com/ikkz/anki-template?tab=readme-ov-file#screenshots)

It turns out the letters isn't being displayed properly in full screen. It looks fine when not in full screen. 

Fullscreen:
![image](https://github.com/user-attachments/assets/0519f04d-a8e4-499d-a7bf-dcd62c490bb8)

Not Fullscreen:
![image](https://github.com/user-attachments/assets/729a8eec-9a08-4bda-8f1d-d75554d977bb)

I hope this helps. Looking forward to your next update.

**Comment by ikkz** [comment]
wrong position of letters has been fixed in https://github.com/ikkz/anki-template/releases/tag/v1.3.2

keep open for answer switch

**Comment by ikkz** [comment]
@aedriandecastro Added a switch to hide answer on the back. Download the latest version here https://github.com/ikkz/anki-template/releases
