### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by TiddlyWorkspace** [ikkz/anki-eco#6]
当选项部分只有图片时卡片显示异常
![image](https://github.com/user-attachments/assets/876d7e29-cd64-417f-9770-9d2d1f7ea049)![image](https://github.com/user-attachments/assets/9f33b29c-8a13-4af0-ae12-b1f5da8020ed)

**Comment by ikkz** [comment]
5 号修复

现在可以通过加入空格暂时避免吗

**Comment by TiddlyWorkspace** [comment]
> 5 号修复
> 
> 
> 
> 现在可以通过加入空格暂时避免吗

可以的

**Comment by ikkz** [comment]
已修复，现在只有 img video 的字段也会显示

https://github.com/ikkz/anki-template/tree/main/mcq
