### ISSUE TITLE
Problem with dark mode

### ISSUE THREAD

**Issue by MohammedElgally** [ikkz/anki-eco#7]
Colors in dark mode are not displaying correctly, you get this dark blue color (I don't know if it's supposed to be like that) while the default color in anki dark mode is kind of gray, I find this a little bit disturbing. I tried to change the color by myself but unfortunately I couldn't. Can you make the dark mode colors like the default color in anki?
![image](https://github.com/user-attachments/assets/6d834712-0080-472a-b798-c7e7118befde)

**Comment by ikkz** [comment]
Fixed, you can download the newest version at https://github.com/ikkz/anki-template/tree/main/mcq

Thanks for your feedback!
