### ISSUE TITLE
Add the True or Flase feature as well

### ISSUE THREAD

**Issue by MasterKed** [ikkz/anki-eco#8]
![Screenshot_20241109_112214_AnkiDroid](https://github.com/user-attachments/assets/a6c26c04-3239-418b-a590-710f8868324f)

**Comment by ikkz** [comment]
Does this meet your needs: use the mcq template and set the "True" option to answer

**Comment by MasterKed** [comment]
No it's like this each false answer causes 1 negative mark, it's common is
Asian medical school exams.

**Comment by ikkz** [comment]
Maybe it should be a new template type instead of a feature of mcq.

I need some time to think about ui and develop it.

**Comment by MasterKed** [comment]
Very grateful for all you have done so far.

**Comment by ikkz** [comment]
I have a preliminary field design about this new template: users should fill two fields: `question` and `items`

`items` must be formatted as a list in Anki editor. Take the question in your picture as an example, the content of `items` will be like:

- T: A body and the adjacent body parts are labelled with the same serial number
- F: Disaster management is governed by disaster management act

every item should start with `T` or `F`, following a colon.

If you have other suggestions please comment below

**Comment by MasterKed** [comment]
Thanks, I'll check it out.

**Comment by MasterKed** [comment]
I think the way you have done is correct, I have to try the template let me
know where to download it

**Comment by ikkz** [comment]
You can download the latest version at https://github.com/ikkz/anki-template/releases

For feedback and suggestions, please open a new issue

**Comment by MasterKed** [comment]
For the Anki dark mode, the font colour of the options are not so great

**Comment by ikkz** [comment]
Fixed
